
services:

  redis:
    image: redis:7-alpine
    container_name: team-dashboard-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - dashboard-network

  postgres:
    image: postgres:15-alpine
    container_name: team-dashboard-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=team_dashboard
      - POSTGRES_USER=dashboard_user
      - POSTGRES_PASSWORD=dashboard_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dashboard-network

  prometheus:
    image: prom/prometheus:latest
    container_name: team-dashboard-prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - dashboard-network

  grafana:
    image: grafana/grafana:latest
    container_name: team-dashboard-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - dashboard-network
    depends_on:
      - prometheus

  influxdb:
    image: influxdb:2-alpine
    container_name: team-dashboard-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=team-dashboard
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=supersecrettoken
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  prometheus_data:
  grafana_data:
  influxdb_data: