apiVersion: v1
kind: ServiceMonitor
metadata:
  name: team-dashboard-metrics
  labels:
    app: team-dashboard
    component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: team-dashboard
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: team-dashboard-alerts
  labels:
    app: team-dashboard
    component: monitoring
spec:
  groups:
  - name: team-dashboard.rules
    rules:
    - alert: HighErrorRate
      expr: |
        (
          rate(http_requests_total{status=~"5.."}[5m]) /
          rate(http_requests_total[5m])
        ) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 10% for 5 minutes"
    
    - alert: HighResponseTime
      expr: |
        histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is above 2 seconds"
    
    - alert: PodCrashLooping
      expr: |
        rate(kube_pod_container_status_restarts_total[15m]) > 0
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping"
    
    - alert: DeploymentReplicasUnavailable
      expr: |
        kube_deployment_status_replicas_unavailable > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Deployment has unavailable replicas"
        description: "Deployment {{ $labels.deployment }} has {{ $value }} unavailable replicas"
    
    - alert: HighMemoryUsage
      expr: |
        (
          container_memory_working_set_bytes{container!="POD",container!=""} /
          container_spec_memory_limit_bytes
        ) > 0.9
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage detected"
        description: "Container {{ $labels.container }} memory usage is above 90%"
    
    - alert: HighCPUUsage
      expr: |
        (
          rate(container_cpu_usage_seconds_total{container!="POD",container!=""}[5m]) /
          container_spec_cpu_quota * 100000
        ) > 80
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
        description: "Container {{ $labels.container }} CPU usage is above 80%"