apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: metrics
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      version: Flux
      organization: team-dashboard
      defaultBucket: metrics
      tlsSkipVerify: true
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    jsonData:
      client: standalone
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true